### ISSUE TITLE
Inline ProvidesSetupInterface and ProvidesStatusInterface and overhaul return types

### ISSUE THREAD

**Issue by bwaidelich** [neos/eventstore#16]
Currently [SetupResult](https://github.com/neos/eventstore/blob/151d285681fa8fbec533499396360f0a08bf9b65/src/Model/EventStore/SetupResult.php) and [Status](https://github.com/neos/eventstore/blob/151d285681fa8fbec533499396360f0a08bf9b65/src/Model/EventStore/Status.php) are DTOs with a string-array of errors, warnings and notices.

This makes it hard to interpret the results from code, e.g. to provide a proper UI or CLI.

The current implementations (`DoctrineCheckpointStorage` and `DoctrineEventStore`) only use:
* `Status::error('not implemented')`
* `SetupResult::success('Table schema is up to date, no migration required')`
* `SetupResult::success('Event store table created/updated successfully')`
* `SetupResult::success('')`

I suggest to remove the two interfaces

```php
interface ProvidesSetupInterface
{
    public function setup(): SetupResult;
}

interface ProvidesStatusInterface
{
    public function status(): Status;
}
```

and instead add the following methods to the `EventStoreInterface`:

```php
interface EventStoreInterface
{
    // ...

    public function setup(): void;
    
    public function status(): EventStoreStatus;
```

`setup()` could be a no-op (for an unlikely event store implementation that needs no setup) and it does not need a return type IMO. Instead, an exception should be thrown if the setup fails (and IMO we don't need a custom exception type since this can't be handled anyways).

For the `status()` return type I could imagine a DTO like this:

```php
enum EventStoreStatusType
{
    case OK;
    case ERROR;
    case REQUIRES_SETUP;
}

final class EventStoreStatus {
    public function __construct(
        public readonly EventStoreStatusType $type,
        public readonly string $details,  
    ) {}
}
```

**Comment by kitsunet** [comment]
Sounds reasonable to me, you can always implement them empty and just return a "Everything is fine" status
